Fix/UI issues new message
Scroll-chatApp/chatApp-frontend pull request #9
Opened 2023-09-11 14:20 UTC by athar-shayan

- Made UI changes 
- Update new message display 
- Made responsive 
- Tried PDF storing properly

2023-09-12 13:44 UTC, imran-munawar requested changes

2023-09-12 13:44 UTC, imran-munawar commented on src/api/index.js
> +    const fetchedConversation = conversation.data;
No need to declare the fetchedConversation, just return directly "return conversation.data"

2023-09-12 13:44 UTC, imran-munawar commented on src/api/index.js
> +  const fetchedUsers = response.data;
no need to declare the fetchedUsers, directly return the "return response.data"

2023-09-12 13:44 UTC, imran-munawar commented on src/component/Chat/ChatArea/chatArea.js
> +            const conversationId = fetchedConversation._id;
don't need to declare conversationId

2023-09-13 06:01 UTC, imran-munawar approved these changes

2023-09-13 07:01 UTC, asad-shayansolution approved these changes

2023-09-13 07:02 UTC, merged